# Importing Libraries and Dataset

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('50_startups.csv')
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
print("Info : \n")
print(df.info())

Info : 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB
None


In [4]:
df.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [6]:
x = df.iloc[:,:-2].values
print("Fist ten input values : \n",x[0:10, :])

y = df.iloc[:,4].values
print("\nFirst ten output values : \n",y[0:10])


Fist ten input values : 
 [[165349.2  136897.8  471784.1 ]
 [162597.7  151377.59 443898.53]
 [153441.51 101145.55 407934.54]
 [144372.41 118671.85 383199.62]
 [142107.34  91391.77 366168.42]
 [131876.9   99814.71 362861.36]
 [134615.46 147198.87 127716.82]
 [130298.13 145530.06 323876.68]
 [120542.52 148718.95 311613.29]
 [123334.88 108679.17 304981.62]]

First ten output values : 
 [192261.83 191792.06 191050.39 182901.99 166187.94 156991.12 156122.51
 155752.6  152211.77 149759.96]


In [7]:
# split ratio 80 : 20

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size = 0.2, random_state=0)

In [8]:
xtrain[:5]

array([[ 55493.95, 103057.49, 214634.81],
       [ 46014.02,  85047.44, 205517.64],
       [ 75328.87, 144135.98, 134050.07],
       [ 46426.07, 157693.92, 210797.67],
       [ 91749.16, 114175.79, 294919.57]])

In [10]:
xtest.shape

(10, 3)

In [11]:
ytest.shape

(10,)

Feature scaling 

In [13]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(xtrain,ytrain)

LinearRegression()

predict the test set results

In [15]:
y_pred = regressor.predict(xtest)
y_pred

array([103901.8969696 , 132763.05993126, 133567.90370044,  72911.78976736,
       179627.92567224, 115166.64864795,  67113.5769057 ,  98154.80686776,
       114756.11555221, 169064.01408795])

In [16]:
y_pred1 = y_pred
y_pred1 = y_pred1.reshape(-1,1)

print("First ten output true value: ", ytest)
print("\n Result of linear regression prediction: ")
print("\nFirst ten predicted value: \n",y_pred1)

First ten output true value:  [103282.38 144259.4  146121.95  77798.83 191050.39 105008.31  81229.06
  97483.56 110352.25 166187.94]

 Result of linear regression prediction: 

First ten predicted value: 
 [[103901.8969696 ]
 [132763.05993126]
 [133567.90370044]
 [ 72911.78976736]
 [179627.92567224]
 [115166.64864795]
 [ 67113.5769057 ]
 [ 98154.80686776]
 [114756.11555221]
 [169064.01408795]]


In [17]:
from sklearn.metrics import mean_squared_error

In [18]:
mean_squared_error(ytest,y_pred1)

77506468.16885409